spacetelescope/poppy

docs/fresnel.rst
poppy/fresnel.py
poppy/optics.py
poppy/poppy_core.py
poppy/tests/test_core.py
poppy/tests/test_errorhandling.py
poppy/tests/test_fresnel.py
poppy/utils.py

This PR addresses a handful of misc issues with Fresnel propagation, including:
- Fixes #242, by enabling the use of Detector instances in FresnelOpticalSystems. A new method on FresnelWavefront will resample a given wavefront onto the desired pixel scale and number of pixels to match the specified detector. To help enable this, Detector pixel scales can now optionally be specified in linear units of e.g. microns/pixel, as well as in angular units like arcsec/pixel. You have to use the linear units for Fresnel detectors. 
- Fixes #191, the lack of a unit test for Detector instances in FresnelOpticalSystems
- Fixes #251, the problem that the test case for "FITSOpticalElement in FresnelOpticalSystem" did not actually use a FresnelOpticalSystem. During the course of fixing this I discovered …

Various small improvements to Fresnel code

---

poppy/utils.py

There's a function to calculate datacubes; we should also be able to display them. This PR extends the `display_psf` function to do so. This is straightforward and doesn't really need much review. 
Related to https://github.com/spacetelescope/webbpsf/issues/116

enable display_psf to handle datacubes from calc_datacube

---

.travis.yml

I did an extensive test diagnostics via #269 (I reset the branch multiple times so not all the commits show). I finally used the WebbPSF's `.travis.yml` file to see if it worked. I then removed each change one by one to find that the `MPLBACKEND` definition fixes the issue we are seeing. This means that the test environment did not know which MPL backend to use. This was weird because Travis showed no errors when it crashed; but now we realize it segfaulted when trying to use/compile MPL & PyPlot.

Fix travis by setting MPLBACKEND

---

poppy/optics.py
poppy/tests/test_optics.py

Adds the new feature requested in #272, a CircularPhaseMask class useful for either old-school Roddier & Roddier coronagraphs, or a Zernike wavefront sensor.

Add CircularPhaseMask coronagraph

---

poppy/fresnel.py
poppy/optics.py
poppy/poppy_core.py
poppy/special_prop.py
poppy/tests/test_core.py
poppy/tests/test_errorhandling.py

This PR fixes #246:
>Currently, the logic in input_wavefront for determining the sampling of the wavefront array is to first look at the pupil size and number of pixels for the first plane in the optical system, and only if those are None does it look to the attributes of the OpticalSystem instance itself. This violates the principle of least astonishment. If the user has specifically set npix or pupil_diam on the OpticalSystem, that should be the first place that is checked when creating an wavefront, and should override whatever the first OpticalElement has.
The result is that input wavefront sizes are determined as following. 
1. If `npix` or `pupil_diameter` are defined on the OpticalSystem as a whole, those values take precedence.
2. Otherwise check if the first OpticalElement in the …

better default parameters for OpticalSystem.input_wavefront 

---

docs/fft_optimization.rst

There was just 1 URL that had to be updated in the poppy docs for spacetelescope - the rest had already been updated

Update URL for spacetelescope repo

---

poppy/conftest.py

Fixes #289 problem with astropy.tests.pytest_plugins. See links to reasoning behind this fix here: https://github.com/spacetelescope/poppy/issues/289#issuecomment-464885028

Fix astropy.tests.pytest_plugins error

---

poppy/__init__.py
poppy/fresnel.py
poppy/instrument.py
poppy/optics.py
poppy/poppy_core.py
poppy/special_prop.py
poppy/tests/test_core.py
poppy/tests/test_errorhandling.py
poppy/tests/test_fresnel.py
poppy/tests/test_instrument.py
poppy/tests/test_special_prop.py
poppy/utils.py
poppy/wfe.py

A relatively substantial refactoring of some core propagation functions. See #280 for more on the motivating use case: passing the outputs of one propagation into the start of another propagation. For instance, this could be used to perform a mixed calculation using Fresnel in some parts and Fraunhofer in others. 
This PR implements this via the following. 
- Refactors most of the core OpticalSystem propagation logic from `propagate_mono` into a new function, tentatively called `propagate_through`, which is a linear operator acting on Wavefront objects. The old `propagate_mono` now becomes a wrapper that creates an input wavefront and passes it through that new function, then handles the output formatting. This preserves the old API and functionality for all existing code, while adding …

Refactoring to enable chaining of optical systems, and mixed Fresnel/Fraunhofer

---

poppy/fresnel.py

Very straightforward- instead of appending an element to the end (default behavior), allow an optical element to be inserted somewhere else in a FresnelOpticalSystem.  This is useful for adding aberration planes to a system that was created elsewhere.

Allow optical elements to be inserted at arbitrary positions along FresnelOpticalSystem

---

poppy/poppy_core.py

This PR is a fix for a reported issue in a STARS ticket.
Issue: "In the file `poppy_core.py`, in `class OpticalElement`, the `display` method has an optional positional argument called `title` which defaults to `None`. Presumably this is so the user can pass in the title to be used in the `display`. However, passing in a title does not work, as the code steps on anything that is provided."
I fixed it so now if `title=None`, the default title structure of "{what your plotting} for {`self.name`}" will remain. But if `title` is not `None`, that input is used for the `title` (or `suptitle` in the case of `what=='both'` since you have 2 subplots)

Update display method in OpticalElement class 

---

docs/classes.rst
docs/fitsheaders.rst
poppy/poppy_core.py
poppy/tests/test_core.py

Certain optics impart a phase which is (approximately) wavelength independent, using a phenomenon sometimes called Pancharatnam-Berry phase [1,2]. This adds support for such optics in FITSOpticalElement with a new `BUNIT` keyword value, `'radian'`, which causes POPPY to treat the phase map as the same number of radians regardless of wavelength.
(This is currently implemented by scaling the phase map to OPD, only to re-scale back to phase in `get_phasor`. This seemed like the best way to preserve backwards-compatibility.)
Fixes #305 
[1] Pancharatnam, S., “Generalized Theory of Interference, and Its Applications. Part I. Coherent Pencils,” Proc. In- dian. Acad. Sci. Sect. A 44, 247 (1956).
[2] Berry, M., “The Adiabatic Phase and Pancharatnams Phase for Polarized Light,” J. Mod. Opt. 34, …

Add FITSOpticalElement support for wavelength-independent phase maps

---

poppy/fresnel.py
poppy/poppy_core.py
poppy/tests/test_fresnel.py

The current implementation of detector-plane resampling for Fresnel propagations uses `scipy.ndimage.zoom`, which appears to result in incorrect amplitude scaling and PSF centering.  This PR replaces this with an alternative implementation which uses `scipy.interpolate.interp2d`, which is better-behaved in both of these aspects.

Use RectBivariateSpline instead of zoom for detector-plane resampling

---

poppy/dms.py
poppy/matrixDFT.py
poppy/optics.py
poppy/poppy_core.py
poppy/tests/test_core.py
poppy/tests/test_misc.py
poppy/tests/test_optics.py

_(Not a super well organized PR; a couple unrelated things in here. To make a long story short, I meant to just PR in the fix to 303, but a couple other recent commits also got swept up in that, and I decided I might as well just go with it rather than redo and split up into multiple PRs)._ 
1. Simplifies the code inside `MultiHexagonAperture`, fixing #303. 
2.  Implements `shift_x` and `shift_y` options for the `ContinuousDeformableMirror` class. Same syntax as for any other optical element, just a different implementation for compatibility with how that class works. 
3. Adds a new function `fixed_sampling_optic` which takes any AnalyticOpticalElement and returns an equivalent ArrayOpticalElement with fixed sampling. This is useful for instance for taking a computationally-slow optic …

Misc handful of small enhancements 

---

poppy/instrument.py

Added new keywords `OPD_FILE` and `OPDSLICE` to the FITS header to separate the information previously held just in `PUPILOPD`. I added these keywords to all the different cases (even though it may not be necessary) to try and keep things consistent.
From issue: https://github.com/spacetelescope/webbpsf/issues/297

Add new OPD keywords

---

poppy/poppy_core.py
poppy/tests/test_errorhandling.py

pretty straightforward: raises errors if you try to add a wavefront to an incompatible wavefront.

stricter checking for wavefront summation. Fixes #308

---

poppy/dms.py

An alternate way to fix #318. See discussion in comments on #319. 
Attention @ivalaginja

allocate sufficient-sized _surface array even if missing center segment. Fixes #318

---

poppy/__init__.py
poppy/dms.py
poppy/optics.py
poppy/wfe.py

The update I just merged in #314 to fix display but #309 caused some trouble for the `ContinousDeformableMirror.display_actuators()` function. Conveniently the fix for this is to substantially simplify `display_actuators` and throw away most of the code in it. :-) This just goes to show that the refactoring in #314 was indeed a good idea. 
An unrelated minor fix that I also included in this PR is to update a few imports and `__all__` lists so a few recently-added classes will now also be in the top `poppy` namespace. E.g. you can now say `poppy.StatisticalPSDWFE` instead of `poppy.wfe.StatisticalPSDWFE`, and `poppy.ContinuousDeformableMirror` instead of `poppy.dms.ContinuousDeformableMirror`.

update ContinousDM.display_actuators to work after PR #314 display refactoring

---

poppy/tests/test_wfe.py
poppy/wfe.py

This PR would remove the ability of WFE classes' `get_opd` functions to accept both Wavefront objects or raw floating-point wavelength values . That behavior was inconsistent with how anything else worked, caused problems (see #199), wasn't used anywhere else in poppy, and wasn't described in the documentation. So I think we can simply drop it, for an overall simplification. 
I replaced it with a wrapper that just checks the input argument is a wavefront and raises an error if not. This could be moved upstream into optics.py later for use on all the optic classes there, if it proves sufficiently useful.

remove _accept_wavefront_or_meters and units args, and related tests, to fix #312 and #199

---

poppy/fresnel.py
poppy/poppy_core.py
poppy/tests/test_errorhandling.py

Trivial bug fix of a float comparison that should be `np.isclose` instead of a strict equality. 
Unrelatedly, also a trivial change to an error string to make the error message clearer.

minor: bugfix for pixel scale comparison in adding wavefronts

---

docs/coronagraphs.rst
poppy/special_prop.py

Fix the display bug in #323 by updating the SemiAnalyticCoronagraph code to use the display helper function added back in #290. Also update the MatrixFTCoronagraph class to also be consistent with the changes in 290.  Lastly, update some of the example code in docs/coronagraphs.rst to Python 3 syntax.

Fix display intermediates in SAMC and MFTC after #290; fixes #323. 

---

poppy/dms.py
poppy/tests/test_dms.py

Depending on the orientation as installed in your optical system, the `(0,0)` actuator is not necessarily in lower left. (In particular for HiCAT DM2 it's in the lower right.) This PR adds a keyword to allow flipping the DM actuator mapping prior to computing the output OPD. 
This is a small and fairly self-explanatory PR. There's a unit test that verifies correct functionality. Should only need a cursory review.

add ability to flip a ContinuousDeformableMirror in X or Y

---

poppy/geometry.py
poppy/optics.py
poppy/poppy_core.py
poppy/tests/test_core.py
poppy/tests/test_fresnel.py
poppy/tests/test_geometry.py
poppy/tests/test_optics.py
poppy/tests/test_special_prop.py
poppy/tests/test_wfe.py
poppy/wfe.py

This branch implements nearly exact sub pixel sampling for circular apertures. This is a fairly subtle effect for well-sampled arrays, but can make a difference in high-precision calculations. And it's an increasingly large effect for small pixel samplings, for instance here's a circle sampled over just 16 pixels: 
The algorithm used is _not_ just a simple N*N subsampling, but rather an implementation of precise geometric calculations of circular arcs through square pixels. Python code originally by Mike Fitzgerald (UCLA), based on older C and IDL code, and provided by him to me some time ago for this use. This sub pixel calculation is applied in the `CircularAperture`, `AnnularFieldStop`, `CircularOcculter` classes's `get_transmission()` functions. It thus can also apply on derived …

Implement gray subpixel sampling for circular apertures

---

poppy/utils.py

In #329 I noticed the Travis build is failing on astropy master. This turns out to be because poppy has been using the `astropy.utils.compat.funcsigs` wrapper, which was deprecated a while ago and has this week been removed from astropy. 
I already had a note we should remove the use of that compatibility once we were in Python 3. This PR does that now.  It's a straightforward swap to `inspect`, now in the standard library.

Replace use of deprecated astropy.utils.compat.funcsigs -> inspect

---

poppy/tests/test_utils.py
poppy/utils.py

The `measure_radial` function already supports normalizing PSFs to their sum=1; this small PR allows that feature to be used from the `measure_ee` and `measure_radius_at_ee` functions too. 
Addresses #332. Attention @ariedel

allow passthrough of normalize keyword in measure_ee and measure_radius_at_ee

---

.travis.yml
environment.yml
setup.py

Updates for minimum versions:
- Add environment.yml for use in setting up Conda environments
- Update minimum supported/required versions of dependencies to the major releases as of 2017. Earlier versions no longer supported. 
These versions are consistent with the similar PR for WebbPSF:  https://github.com/spacetelescope/webbpsf/pull/321

Add environment.yml; update minimum deps to major versions as of 2017

---

poppy/instrument.py

I'm working with @mperrin on PSF subtraction and came across a scenario where I wanted to generate a data cube with more than 100 slices but was hit with an error -- `ValueError: Maximum number of wavelengths exceeded. Cannot be more than 100`. 
I brought it up to Marshall and he couldn't remember why this limit existed, so I'm proposing a pull request that removes it from `instrument.py` to see what `poppy`'s other developers think.

Remove wavelength limit from instrument.py

---

poppy/utils.py

As of numpy 1.12 passing a non-integer number of samples for logspace() was deprecated. As of numpy 1.18, this is now mandatory, yielding an error when you do pass a float anyway.

Fix logspace() calls for numpy 1.18+

---

.travis.yml

Minor update to 'lowest supported versions' test case: astropy 4.0 is released now, but we still support 3.2.

update travis test setup for py3.5, limit to astropy < 4
